### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Commifreak** [thom-nic/openfire-jboss-clustering#1]
Hey,

i've found your Topic @ IgniteRealtime Community by searching for a solution for a new clustering software for my jabber server.

After i have read your topic you give me hope to found it :)

Has your software a good future? How many peoples are working on this project?

In the case for a good future for this software, i would help you - but only with a translation of it (if necessary ;) ) because i didnt have any java skills xD

I hope i can help.

Please answer :D

Greetzs,
CF

**Comment by thom-nic** [comment]
Two ppl currently working on it.  We hope to have a fully functional plugin w/in the next month or two.  Feel free to branch and update documentation.
